### ISSUE TITLE
hi，how to use the plugin？

### ISSUE THREAD

**Issue by JustgoFlyme** [jaroslav-kuchar/MultiColourRenderer#1]
I have installed the multicolourRenderer and create colourList, but preview is always working, I need your help.

**Comment by JiriKrizek** [comment]
You need to have colourList attribute set for each node. Values should be delimited by , (comma character). 
For example, set attribute colourList for some node to [16711680,65280,255] and it should be visualized as three-coloured node in Preview window.

**Comment by JustgoFlyme** [comment]
I got it, thanks!
